config/routes.rb
Rails.application.routes.draw do
  # get "/books",to: "books#index"
  # post "/books",to: "books#create"
  # get "/books/new",to: "books#new",as:"new_book"
  # get "/books/:id/edit",to: "books#edit",as:"edit_book"
  # get "/books/:id",to: "books#show",as:"book"
  # patch "/books/:id",to: "books#update"
  # delete "/books/:id",to: "books#destroy"
  resources :books

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/signin", to: "session#new"
  post "/signin", to: "session#create"
  get "/signout", to: "session#destroy"
  get "/users/edit", to: "users#edit", as: "edit_user"
  patch "/users", to: "users#update", as: "user"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    belongs_to :user

    validates :year,presence: true
    validates :month,presence: true
    validates :inout,presence: true
    validates :category,presence: true
    validates :amount,presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :books

    validates :name, presence: true, length: {maximum: 20}
    validates :email, presence: true, uniqueness: true, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def redirect_to_signin
        redirect_to signin_path if session[:user_id].blank?
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :set_book, only:[:show, :edit, :update, :destroy]
    before_action :redirect_to_signin

    def index
        @books = Book.where(user_id: session[:user_id])
        @books = @books.where(year: params[:year]) if params[:year].present?
        @books = @books.where(month: params[:month]) if params[:month].present?
    end

    def show
    end

    def new
        @book = Book.new
        @book.year =2019
    end

    def create
        book_params = params.require(:book).permit(:year, :month, :inout,
        :category, :amount)
        book_params[:user_id] = session[:user_id]
        @book = Book.new(book_params)
        if @book.save
            flash[:notice] = "家計簿にデータを1件登録しました"
            redirect_to books_path
        else
            flash.now[:alert] = "登録に失敗しました。"
            render :new
        end
    end

    def edit
    end

    def update
        book_params = params.require(:book).permit(:year, :month, :inout, :category, :amount)
        if @book.update(book_params)
            flash[:notice] = "データを1件更新しました。"
            redirect_to books_path
        else
            flash.now[:alert] = "更新に失敗しました。"
            render :edit
        end
    end

    def destroy
        @book.destroy
        flash[:notice] = "削除しました。"
        redirect_to books_path
    end

    def set_book
        @book = Book.where(user_id: session[:user_id]).find(params[:id])
    end

    private
    def set_book
        @book=Book.find(params[:id])
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    before_action :redirect_to_books, only: [:new, :create]
    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            flash[:notice] = "ログインしました"
            session[:user_id] = user.id
            redirect_to books_path
        else
            flash.now[:alert] = "failed"
            render "new"
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to signin_path
    end

    private
    def redirect_to_books
        redirect_to books_path if session[:user_id].present?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :redirect_to_signin, only: [:edit, :update]

    def new
        @user =User.new
    end

    def create
        user_params = params.require(:user).permit(:name, :email, :password, :passwprd_confirmation)
        @user = User.new(user_params)
        if @user.save
            flash[:notice] ="登録しました"
            redirect_to signin_path
       else
            flash.now[:alert] = "登録に失敗しました"
            render "new"
       end
    end

    def destroy
        session[:user_id] = nil
        redirect_to signin_path
    end

    def edit
        @user = User.find(session[:user_id])
    end

    def update
        @user = User.find(session[:user_id])
        user_params = params.require(:user).permit(:name, :email)
        if @user.update(user_params)
            flash[:notice] = "更新しました"
            redirect_to edit_user_path
        else
            flash.now[:alert] = "更新に失敗しました"
            render "edit"
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<h1>家計簿<%= type %></h1>
<%= form_with model: book,local: true, method:method do |f|%>
    <div class="form-group">
        <label>年度</label>
        <%= f.number_field :year,class: "form-control"%>
    </div>
    <div class="form-group">
        <label>月</label>
        <%= f.number_field :month,class: "form-control"%>
    </div>
    <div class="form-group">
        <label>区分</label>
        <%= f.select :inout,[["収入",1],["支出",2]],{},{class: "form-control"}%>
    </div>
    <div class="form-group">
        <label>科目</label>
        <%= f.text_field :category,class: "form-control"%>
    </div>
    <div class="form-group">
        <label>金額</label>
        <%= f.number_field :amount,class: "form-control"%>
    </div>
    <%= link_to "戻る",books_path,class:"btn btn-secondary"%>
    <%= f.submit type,class:"btn btn-primary"%>
<% end %>

app/views/books/edit.html.erb
<%= render partial: "form", locals:{type: "更新",book: @book,method: "patch"} %>

app/views/books/index.html.erb
<h1>家計簿</h1>
<div class="card">
    <div class="card-body"></div>
        <%= form_with method: "get",local: true do |f| %>
            <div class="form-row">
                <div class="col">
                    <%= f.number_field "year",placeholder: "年度を入力",class: "form-control" %>
                </div>
                <div class="col">
                    <%= f.number_field "year",placeholder: "対象月を入力",class: "form-control" %>
                </div>
                <div class="col">
                    <%= f.submit "検索",class: "btn btn-primary" %>
                </div>
            </div>
        <% end %>
    </div>
</div>

<%= link_to "新規",new_book_path,class:"btn btn-success" %>
<table class ="table table-striped">
    <tr>
        <th>年月</th>
        <th>区分</th>
        <th>科目</th>
        <th>金額</th>
    </tr>
    <% sum=0 %>
    <% @books.each do |book| %>
    <tr>
        <td><%= book.year %>年<%= book.month %>月</td>
        <td><%= book.inout %></td>
        <td><%= book.category %></td>
        <td><%= book.amount %>万円</td>
        <td>
          <%= link_to "詳細",book_path(book),class:"btn btn-info" %>
          <%= link_to "編集",edit_book_path(book),class:"btn btn-warning" %>
          <%= link_to "削除",book_path(book),method: :delete ,data:{confirm:'削除しますか？'},class:"btn btn-danger" %>
        </td>
    </tr>
        <% if book.inout == 1 %>
          <% sum += book.amount %>
        <% else %>
          <% sum -= book.amount %>
        <% end %>
    <% end %>
    <tr>
      <td></td>
      <td></td>
      <td>合計</td>
      <td><%= sum %>万円</td>
      <td></td>
    </tr>
</table>

app/views/books/new.html.erb
<%= render partial: "form", locals:{type: "登録",book: @book,method: nil} %>

app/views/books/show.html.erb
<h1>家計簿詳細</h1>
<table class="table table-striped">
    <tr>
        <th>年月</th>
        <td><%= @book.year %>年<%= @book.month%>月</td>
    </tr>
    <tr>
        <th>区分</th>
        <td><%= @book.inout %></td>
    </tr>
    <tr>
        <th>科目</th>
        <td><%= @book.category %></td>
    </tr>
    <tr>
        <th>金額</th>
        <td><%= @book.amount %>万円</td>
    </tr>
</table>
<%= link_to "戻る",books_path,class:"btn btn-secondary"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kakeibo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
    <div class="navbar-brand">家計簿アプリ</div>
    <div>
    <% if session[:user_id].present? %>
     <%= link_to "登録内容の更新", edit_user_path, class: "btn btn-outline-info"%>
     <%= link_to "ログアウト", signout_path, class: "btn btn-outline-secondary" %>
    <% else %>
      <%= link_to "会員登録",signup_path,class:"btn btn-outline-primary"%>
    <% end %>
    </div>
    </nav>
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger" role="alert">
          <%= flash[:alert] %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  </body>
</html>

app/views/session/new.hrml.erb
<h1>ログイン</h1>
<%= form_with url: signin_path, local: true do |f| %>

<div class="form-group">
<label>メールアドレス</label>
<%= f.text_field :email, class: "form-control" %>
</div>
<div class="form-group">
<label>パスワード</label>
<%= f.password_field :password, class: "form-control" %>
</div>
<%= f.submit "ログイン", class: "btn btn-primary"%>
<% end %>

app/views/session/new.html.erb
<h1>ログイン</h1>
<%= form_with url: signin_path, local: true do |f| %>

<div class="form-group">
<label>メールアドレス</label>
<%= f.text_field :email, class: "form-control" %>
</div>
<div class="form-group">
<label>パスワード</label>
<%= f.password_field :password, class: "form-control" %>
</div>
<%= f.submit "ログイン", class: "btn btn-primary"%>
<% end %>

app/views/users/edit.html.erb
<h1>会員情報更新</h1>
<%= form_with model: @user, url: user_path, method: "patch", local: true do |f|
%>

app/views/users/new.html.erb
<h1>会員登録</h1>
<%= form_with model: @user, url: signup_path, local: true do |f| %>

<div class="form-group">
    <label>名前</label>
    <%= f.text_field :name, class: "form-control" %>
</div>
<div class="form-group">
<label>メールアドレス</label>
<%= f.text_field :email, class: "form-control" %>
</div>
<div class="form-group">
<label>パスワード</label>
<%= f.password_field :password, class: "form-control" %>
</div>
<div class="form-group">
<label>パスワード確認用</label>
<%= f.password_field :password_confirmation, class: "form-control" %>
</div>
<%= f.submit "登録", class: "btn btn-primary"%>
<% end %>